//! What the readers returned before they were rewritten, recorded case by case.
//!
//! `tests/fixtures/reader-expected.txt` was generated by this file running against the
//! implementation that decoded a whole span into one buffer, and is what the current one is
//! measured against: same bytes out, or the same error, for every case below.
//!
//! Inputs are generated here rather than stored, from `ChaCha8Rng` with fixed seeds — `StdRng`
//! is allowed to change its output between releases, so it cannot be used to reproduce a corpus.
//! The bodies are then compressed by this crate, so the fixture also pins the compressor: a
//! change there moves the frame boundaries and the expected outputs with them.
//!
//! Regenerate with `SEEKZSTDSEP_REGEN=1 cargo test --test reader_fixture`, and only when the
//! change in behaviour is intended and stated.

use std::fmt::Write as _;
use std::fs::File;
use std::io::Cursor;
use std::path::{Path, PathBuf};

use memchr::memmem::Finder;
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use zeekstd::Decoder;

use seekzstdsep::seekzstdsep_lib::{
    cnt_of_separetor_in_frame, records_between_by_separator_in_frame, seek_table_decomp_frames,
};
use seekzstdsep::{CompressOptions, RecordReader, compress_to_seekable_zst_with_opts};

const FRAME_SIZE: usize = 8192;

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/reader-expected.txt")
}

/// FNV-1a, so a case's result is one short token and the fixture stays diffable. Written out
/// rather than taken from a crate: the fixture has to mean the same thing in both checkouts.
fn digest(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

/// Runs `f`, turning a panic into an outcome so the fixture pins those too — one of the inputs
/// below has no separator in frame 0, which `docs/bugs.md` records as a division by zero.
fn guard(f: impl FnOnce() -> String) -> String {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(s) => s,
        Err(p) => format!(
            "panic {}",
            p.downcast_ref::<String>()
                .cloned()
                .or_else(|| p.downcast_ref::<&str>().map(|s| s.to_string()))
                .unwrap_or_default()
        ),
    }
}

/// One case's outcome, as the fixture records it. Errors name the input by its file name: the
/// directory is a fresh temporary one on every run.
fn outcome(result: anyhow::Result<Vec<u8>>) -> String {
    match result {
        Ok(bytes) => format!("ok {} {:016x}", bytes.len(), digest(&bytes)),
        Err(e) => format!("err {}", strip_dir(&e.to_string())),
    }
}

/// Replaces any absolute path in `msg` with its file name.
fn strip_dir(msg: &str) -> String {
    msg.split_whitespace()
        .map(|w| match w.rsplit_once('/') {
            Some((head, name)) if head.starts_with('/') => name,
            _ => w,
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Records of random lengths, salted with the separator's first byte so partial matches occur,
/// sometimes ending in a fragment.
fn random_body(seed: u64, separator: &[u8]) -> Vec<u8> {
    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    let n = rng.random_range(0..=200);
    let mut body = Vec::new();
    for _ in 0..n {
        let len = rng.random_range(0..300);
        for _ in 0..len {
            let b = if rng.random_bool(0.1) {
                separator[0]
            } else {
                rng.random_range(b'a'..=b'z')
            };
            body.push(b);
        }
        body.extend_from_slice(separator);
    }
    if !body.is_empty() && rng.random_bool(0.3) {
        for _ in 0..rng.random_range(1..200) {
            body.push(rng.random_range(b'a'..=b'z'));
        }
    }
    body
}

/// A separator straddling the 32768-byte read the window fills, then ordinary records.
fn boundary_body(separator: &[u8]) -> Vec<u8> {
    let mut body = vec![b'a'; 32768 - separator.len()];
    body.extend_from_slice(separator);
    for i in 0..50u8 {
        body.extend(std::iter::repeat(b'b' + (i % 20)).take(997));
        body.extend_from_slice(separator);
    }
    body
}

/// Records several times the window, which no single read can hold.
fn giant_body(separator: &[u8]) -> Vec<u8> {
    let mut body = Vec::new();
    for i in 0..3u8 {
        body.extend(std::iter::repeat(b'g' + i).take(100_000));
        body.extend_from_slice(separator);
        body.extend(std::iter::repeat(b's' + i).take(50));
        body.extend_from_slice(separator);
    }
    body
}

fn compress(dir: &Path, label: &str, body: &[u8], separator: &[u8]) -> PathBuf {
    let out_path = dir.join(format!("{label}.seek.zst"));
    compress_to_seekable_zst_with_opts(
        Cursor::new(body.to_vec()),
        &mut std::io::sink(),
        FRAME_SIZE,
        true,
        separator,
        None,
        Some(CompressOptions {
            out_dir: Some(dir.to_path_buf()),
            out_path: Some(out_path.clone()),
            ..Default::default()
        }),
    )
    .expect("Failed to compress");
    out_path
}

fn decoder(path: &Path) -> Decoder<'static, File> {
    Decoder::new(File::open(path).expect("Failed to open compressed file")).expect("no decoder")
}

/// Every case for one input file, as `id\toutcome` lines.
fn cases_for(out: &mut String, label: &str, path: &Path, separator: &[u8]) {
    let finder = Finder::new(separator);
    let frames = seek_table_decomp_frames(&decoder(path)).expect("no frames");
    let last = frames.len() - 1;

    // Range reads over one frame, and over the whole file.
    let mut spans: Vec<(usize, usize)> = (0..frames.len()).map(|i| (i, i)).collect();
    spans.push((0, last));
    for (fi, fj) in spans {
        let start = frames[fi].0;
        let len = frames[fj].0 + frames[fj].1 - start;
        for skip in [0u64, 1, 7] {
            for cnt in [0u64, 1, 25] {
                let r = guard(|| {
                    outcome(records_between_by_separator_in_frame(
                        &mut decoder(path),
                        start,
                        len,
                        skip,
                        cnt,
                        &finder,
                        separator,
                    ))
                });
                let _ = writeln!(out, "{label}\trange\t{fi}\t{fj}\t{skip}\t{cnt}\t{r}");
            }
        }
        let c = guard(|| {
            match cnt_of_separetor_in_frame(&mut decoder(path), start, len, &finder, separator) {
                Ok(n) => format!("ok {n}"),
                Err(e) => format!("err {}", strip_dir(&e.to_string())),
            }
        });
        let _ = writeln!(out, "{label}\tcount\t{fi}\t{fj}\t{c}");
    }

    // The reader's own surface.
    let meta = guard(|| {
        let mut reader = RecordReader::open(path.to_path_buf(), separator).expect("no reader");
        format!(
            "{}\t{}\t{}",
            reader.frame_count(),
            reader.records_per_frame(),
            match reader.total_records() {
                Ok(n) => format!("ok {n}"),
                Err(e) => format!("err {}", strip_dir(&e.to_string())),
            }
        )
    });
    let _ = writeln!(out, "{label}\tmeta\t{meta}");

    for index in [0usize, 1, 116, 117, 300, 10_000] {
        let r = guard(|| {
            let mut reader = RecordReader::open(path.to_path_buf(), separator).expect("no reader");
            match reader.record(index) {
                Ok(Some(bytes)) => format!("ok {} {:016x}", bytes.len(), digest(&bytes)),
                Ok(None) => "none".to_string(),
                Err(e) => format!("err {}", strip_dir(&e.to_string())),
            }
        });
        let _ = writeln!(out, "{label}\trecord\t{index}\t{r}");
    }
    for from in [0usize, 1, 117, 300] {
        for cnt in [1usize, 2, 117] {
            let r = guard(|| {
                let mut reader =
                    RecordReader::open(path.to_path_buf(), separator).expect("no reader");
                outcome(reader.records(from, cnt))
            });
            let _ = writeln!(out, "{label}\trecords\t{from}\t{cnt}\t{r}");
        }
    }

    // Every record in order, as one digest over the whole sequence.
    let iter = guard(|| {
        let reader = RecordReader::open(path.to_path_buf(), separator).expect("no reader");
        let mut all = Vec::new();
        let mut n = 0usize;
        for item in reader.into_records() {
            match item {
                Ok(bytes) => {
                    n += 1;
                    all.extend_from_slice(&bytes);
                }
                Err(e) => return format!("err {}", strip_dir(&e.to_string())),
            }
        }
        format!("ok {n} {} {:016x}", all.len(), digest(&all))
    });
    let _ = writeln!(out, "{label}\titer\t{iter}");
}

/// Every case over every input, in a fixed order.
fn all_cases(dir: &Path) -> String {
    let mut out = String::new();
    for seed in 0..3u64 {
        for separator in [b"\n".as_slice(), b"\r\n", b"@@@"] {
            let label = format!("random-{seed}-{}", separator.len());
            let body = random_body(seed, separator);
            let path = compress(dir, &label, &body, separator);
            cases_for(&mut out, &label, &path, separator);
        }
    }
    let path = compress(dir, "no-separator", &vec![b'x'; 5000], b"\n");
    cases_for(&mut out, "no-separator", &path, b"\n");

    let sep: &[u8] = b"\r\n";
    let path = compress(dir, "boundary", &boundary_body(sep), sep);
    cases_for(&mut out, "boundary", &path, sep);

    let path = compress(dir, "giant", &giant_body(b"\n"), b"\n");
    cases_for(&mut out, "giant", &path, b"\n");
    out
}

#[test]
fn readers_match_the_recorded_behaviour() {
    // Several cases panic by design; the hook would otherwise print each one.
    let hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    let dir = tempfile::tempdir().expect("Failed to create temp dir");
    let got = all_cases(dir.path());
    std::panic::set_hook(hook);

    if std::env::var("SEEKZSTDSEP_REGEN").is_ok() {
        std::fs::write(fixture_path(), &got).expect("Failed to write the fixture");
        eprintln!("regenerated {}", fixture_path().display());
        return;
    }

    let want = std::fs::read_to_string(fixture_path()).expect("Failed to read the fixture");
    if got == want {
        return;
    }
    let first = want
        .lines()
        .zip(got.lines())
        .find(|(w, g)| w != g)
        .map(|(w, g)| format!("\n  recorded: {w}\n  now:      {g}"))
        .unwrap_or_else(|| {
            format!(
                "\n  case counts differ: recorded {} lines, now {} lines",
                want.lines().count(),
                got.lines().count()
            )
        });
    panic!("the readers no longer return what the fixture records:{first}");
}
